### PR TITLE
Add the `prop.alias` API to generate a shortcut for the `ID attribute` of the `Ref field`

### PR DESCRIPTION
**Pull request by nanyuantingfeng**
```typescript

   class Person extends Model {
      public static type = 'person';

      @prop.toOne(Person) public spouse!: Person;
      @prop.alias('spouse') public spouseId!: number;
    }

/*
 if   person.spouse = otherPerson;
 person.spouseId will be auto set value by otherPersion.id

if   person.spouseId = otherPersion.id 
 person.spouse will be auto set value by otherPerson
*/
```

### CODE REVIEW

**Comment by DarkoKukovec** [comment]
Hi @nanyuantingfeng,

Thank you for your contribution.
Based on the quick look, the code itself looks good, but I'm wondering what's the reasoning behind this change.

My concerns regarding this feature:
- `alias` is not exactly a good naming for this as it's not an alias, but an id of the referenced model.
- would this work only for `toOne`?
- why would you need multiple aliases for the same field?
- how is this different than just a regular computed property
```typescript
class Person extends Model {
  public static type = 'person';

  @prop.toOne(Person) public spouse!: Person;
  @computed get spouseId() {
    return this.spouse ? this.spouse.meta.id : undefined;

	// Or an alternative
	return this.meta.refs.spouse;
  }
}
```

I'm not really a fan of adding a feature that can be implemented manually almost as easy 😕 

Also, I would rather not add any new features to v1, since the v2 is basically in the release candidate phase.

**Comment by nanyuantingfeng** [comment]
> The reference field name for the backend data structure design is often the `xxxxId`, such as `Staff -> departmentId`.
I want to use `department` as the reference key in the datx structural rather than the `departmentId`,If `departmentId` ref a `Department` is very strange.
so I'd like to have this feature, `xxxxId` attributes can keep from the backend data, and `xxxx` can also refer to the correct ref value.

**Comment by DarkoKukovec** [comment]
Ok, got it, but I'm still not convinced this is the best approach to the problem.

This is actually solved in the v2: https://datx.dev/docs/next/api-reference/attribute#parse
(keep in mind that in v2 `@prop` is renamed to `@Attribute`):
```typescript
class Person extends Model {
  public static type = 'person';

  // The parse method gets the "spouse" property (which is not relevant for you) and the whole object
  @Attribute({ toOne: Person, parse: (value, data) => data.spouseId })
  public spouse!: Person;
}
```

Would something like that work for your use case?

**Comment by nanyuantingfeng** [comment]
Yep. that's what I want. 
Thanks. Looking forward to the official V2 release

**Pull request closed without merging**
