### PR TITLE
MobX 6 support

### PR DESCRIPTION
**Pull request by DarkoKukovec**

### CODE REVIEW

**Comment by svobik7** [comment]
Hello @DarkoKukovec , are you planing MobX 6 support for Datx v1?

**Comment by DarkoKukovec** [comment]
Hi @svobik7,

Not for DatX 1, but DatX 2 already has support for it.

**Comment by svobik7** [comment]
Ok, is there any schedule on v2 public release?

**Comment by DarkoKukovec** [comment]
I'm guessing sometime within the next month, but the beta should be quite stable - we're already using it on few of our client projects.

**Pull request merged**
